name: Publish package to GitHub Packages
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@octocat'
      - name: Set package version
        run: |
          # Get the version from the release tag
          VERSION=$(echo "${{ github.ref }}" | sed -n 's|^refs/tags/v\(.*\)|\1|p')
          # Update the package.json version
          npm version "${VERSION}"
          # Commit the updated package.json
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Set version to ${VERSION}"
      - run: npm build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
